import { ProcessingResult } from './imageEngine';

/**
 * Real Local URL Encoder / Decoder
 */
export function processUrlEncoding(input: string, mode: 'encode' | 'decode' = 'encode'): ProcessingResult {
  try {
    if (!input) throw new Error('URL string is required.');
    const result = mode === 'encode' ? encodeURIComponent(input) : decodeURIComponent(input);
    const blob = new Blob([result], { type: 'text/plain' });

    return {
      success: true,
      outputBlob: blob,
      outputUrl: URL.createObjectURL(blob),
      outputFileName: `${mode}_url.txt`,
      data: result,
      outputSize: blob.size
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : 'URL processing error.';
    return {
      success: false,
      error: `URL ${mode} error: ${errorMsg}`
    };
  }
}

/**
 * Real Local OpenGraph Meta Tag Generator
 */
export function generateMetaTags(title: string = 'BrandEX Utilities', description: string = 'Universal local software utilities.', url: string = 'https://brandex.co.in'): ProcessingResult {
  try {
    const metaHtml = `<!-- OpenGraph & SEO Meta Tags Generated by BrandEX -->
<title>${title}</title>
<meta name="description" content="${description}">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:url" content="${url}">
<meta property="og:type" content="website">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${title}">
<meta name="twitter:description" content="${description}">`;

    const blob = new Blob([metaHtml], { type: 'text/html' });

    return {
      success: true,
      outputBlob: blob,
      outputUrl: URL.createObjectURL(blob),
      outputFileName: 'meta_tags.html',
      data: metaHtml,
      outputSize: blob.size
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : 'Meta tag generation failed.';
    return {
      success: false,
      error: `Meta tag generator error: ${errorMsg}`
    };
  }
}

/**
 * Real Local Lorem Ipsum Generator
 */
export function generateLoremIpsum(paragraphs: number = 3): ProcessingResult {
  try {
    const loremBase = [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit.'
    ];

    const resultParagraphs = [];
    for (let i = 0; i < paragraphs; i++) {
      resultParagraphs.push(loremBase[i % loremBase.length]);
    }

    const text = resultParagraphs.join('\n\n');
    const blob = new Blob([text], { type: 'text/plain' });

    return {
      success: true,
      outputBlob: blob,
      outputUrl: URL.createObjectURL(blob),
      outputFileName: 'lorem_ipsum.txt',
      data: text,
      outputSize: blob.size
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : 'Lorem ipsum generation failed.';
    return {
      success: false,
      error: `Lorem generator error: ${errorMsg}`
    };
  }
}

/**
 * Real Local Favicon Package Generator
 */
export async function generateFaviconPackage(file?: File): Promise<ProcessingResult> {
  try {
    const canvas = document.createElement('canvas');
    canvas.width = 32;
    canvas.height = 32;
    const ctx = canvas.getContext('2d');

    if (ctx) {
      if (file) {
        const bitmap = await createImageBitmap(file);
        ctx.drawImage(bitmap, 0, 0, 32, 32);
      } else {
        ctx.fillStyle = '#0F172A';
        ctx.fillRect(0, 0, 32, 32);
        ctx.fillStyle = '#4F46E5';
        ctx.fillRect(8, 8, 16, 16);
      }
    }

    const blob = await new Promise<Blob>((res) => canvas.toBlob(b => res(b!), 'image/x-icon'));
    const outputUrl = URL.createObjectURL(blob);

    return {
      success: true,
      outputBlob: blob,
      outputUrl,
      outputFileName: 'favicon.ico',
      outputSize: blob.size,
      data: 'Generated standard 32x32 Favicon icon in browser memory.'
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : 'Favicon generation failed.';
    return {
      success: false,
      error: `Favicon generator error: ${errorMsg}`
    };
  }
}

/**
 * Real Local Query Parameter Sorter (Alphabetical Canonicalization)
 */
export function sortQueryParams(urlString: string): ProcessingResult {
  try {
    const parsed = new URL(urlString.trim());
    const keys = Array.from(parsed.searchParams.keys()).sort();
    const sortedParams = new URLSearchParams();

    keys.forEach(k => {
      const values = parsed.searchParams.getAll(k);
      values.forEach(v => sortedParams.append(k, v));
    });

    parsed.search = sortedParams.toString();
    const canonicalUrl = parsed.toString();
    const blob = new Blob([canonicalUrl], { type: 'text/plain' });

    return {
      success: true,
      outputBlob: blob,
      outputUrl: URL.createObjectURL(blob),
      outputFileName: 'canonical_url.txt',
      data: canonicalUrl,
      outputSize: blob.size
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : 'Failed to sort query parameters.';
    return { success: false, error: errorMsg };
  }
}

/**
 * Real Local Query Parameter Extractor
 */
export function extractQueryParams(urlString: string): ProcessingResult {
  try {
    const parsed = new URL(urlString.trim());
    const params: Record<string, string | string[]> = {};

    parsed.searchParams.forEach((val, key) => {
      if (key in params) {
        if (Array.isArray(params[key])) {
          (params[key] as string[]).push(val);
        } else {
          params[key] = [params[key] as string, val];
        }
      } else {
        params[key] = val;
      }
    });

    const report = {
      origin: parsed.origin,
      pathname: parsed.pathname,
      totalParameters: Object.keys(params).length,
      parameters: params
    };

    const formatted = JSON.stringify(report, null, 2);
    const blob = new Blob([formatted], { type: 'application/json' });

    return {
      success: true,
      outputBlob: blob,
      outputUrl: URL.createObjectURL(blob),
      outputFileName: 'extracted_params.json',
      data: formatted,
      outputSize: blob.size
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : 'Failed to extract query parameters.';
    return { success: false, error: errorMsg };
  }
}

/**
 * Real Local HTML Link & Asset Extractor
 */
export function extractHtmlLinks(htmlContent: string): ProcessingResult {
  try {
    if (typeof window === 'undefined') {
      throw new Error('HTML parsing requires a DOM browser environment.');
    }

    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlContent, 'text/html');

    const links = Array.from(doc.querySelectorAll('a[href]')).map(a => a.getAttribute('href') || '');
    const images = Array.from(doc.querySelectorAll('img[src]')).map(img => img.getAttribute('src') || '');
    const scripts = Array.from(doc.querySelectorAll('script[src]')).map(s => s.getAttribute('src') || '');
    const stylesheets = Array.from(doc.querySelectorAll('link[rel="stylesheet"]')).map(l => l.getAttribute('href') || '');

    const report = {
      totalAnchors: links.length,
      anchors: Array.from(new Set(links)),
      totalImages: images.length,
      images: Array.from(new Set(images)),
      totalScripts: scripts.length,
      scripts: Array.from(new Set(scripts)),
      totalStylesheets: stylesheets.length,
      stylesheets: Array.from(new Set(stylesheets))
    };

    const formatted = JSON.stringify(report, null, 2);
    const blob = new Blob([formatted], { type: 'application/json' });

    return {
      success: true,
      outputBlob: blob,
      outputUrl: URL.createObjectURL(blob),
      outputFileName: 'html_links_report.json',
      data: formatted,
      outputSize: blob.size
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : 'Failed to extract HTML links.';
    return { success: false, error: errorMsg };
  }
}
